### ISSUE TITLE
Merge train sub-meshes

### ISSUE THREAD

**Issue by DethRaid** [BVE-Reborn/bve-reborn#22]
Merge train sub-meshes into a single mesh

You'll also have to merge the sub-mesh textures into a single texture atlas, and adjust the texture coordinates of each sub-mesh to refer to the texture's place in the atlas

The per-sub-mesh data can just be baked into the vertex data, modern GPUs have bigger problems than a few more vertex bytes

**Comment by DethRaid** [comment]
I think this is the highest priority for me

**Comment by cwfitzgerald** [comment]
This turned out to be futile due to a variety of issues. We'd need bindless/DI to get this to happen, closing for now.

**Comment by DethRaid** [comment]
Cry
