### ISSUE TITLE
Translate command processing all commands instead of only one

### ISSUE THREAD

**Issue by Railfan007** [BVE-Reborn/bve-reborn#64]
### Description
When Cylinder and Cube commands are under the same CreateMeshBuilder command, Translate works for all Cylinder/Cube commands, and not each command individually. I also isolated the commands into a separate file and tried again, same issue. The documentation page says it should not be happening with such commands here: https://openbve-project.net/documentation_hugo/en/objects/native/csv.html#translate

### Reproduction
https://media.discordapp.net/attachments/694077682333253664/699968428210913320/unknown.png

`CreateMeshBuilder ;;1`
`Cylinder,8,0.05,0.08,0.06`
`Translate,-1.425,-0.135,0.12`
`Cube,0.1,0.02,0.1`
`;Translate,-1.425,-0.17,.12 ;remove/add the semicolon in front of Translate to produce issue`
`;SetColor,150,150,150`

### Related information 
* Operating system = Win 10
* Method of control = Keyboard and Mouse

Link to the OpenBVE issue also filed: https://github.com/leezer3/OpenBVE/issues/460

**Comment by cwfitzgerald** [comment]
Per OpenBVE issue, this is the correct behavior.
